set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[0]}]

set_property PACKAGE_PIN E1 [get_ports {camera_data[7]}]
set_property PACKAGE_PIN D1 [get_ports {camera_data[6]}]
set_property PACKAGE_PIN G2 [get_ports {camera_data[5]}]
set_property PACKAGE_PIN F1 [get_ports {camera_data[4]}]
set_property PACKAGE_PIN H2 [get_ports {camera_data[3]}]
set_property PACKAGE_PIN G1 [get_ports {camera_data[2]}]
set_property PACKAGE_PIN J1 [get_ports {camera_data[1]}]
set_property PACKAGE_PIN J2 [get_ports {camera_data[0]}]
set_property PACKAGE_PIN Y22 [get_ports {rgmii_txd[3]}]
set_property PACKAGE_PIN W21 [get_ports {rgmii_txd[2]}]
set_property PACKAGE_PIN W22 [get_ports {rgmii_txd[1]}]
set_property PACKAGE_PIN U21 [get_ports {rgmii_txd[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports camera_href]
set_property IOSTANDARD LVCMOS33 [get_ports camera_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports camera_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports camera_sdat]
set_property IOSTANDARD LVCMOS33 [get_ports camera_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports camera_xclk]
set_property IOSTANDARD LVCMOS33 [get_ports clk_pixel]
set_property IOSTANDARD LVCMOS33 [get_ports clk_sys]
set_property IOSTANDARD LVCMOS33 [get_ports mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio]
set_property IOSTANDARD LVCMOS33 [get_ports phy_config_done]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

set_property PACKAGE_PIN A1 [get_ports camera_href]
set_property PACKAGE_PIN N20 [get_ports camera_rst_n]
set_property PACKAGE_PIN M20 [get_ports camera_sclk]
set_property PACKAGE_PIN L18 [get_ports camera_sdat]
set_property PACKAGE_PIN B2 [get_ports camera_vsync]
set_property PACKAGE_PIN M17 [get_ports camera_xclk]
set_property PACKAGE_PIN B1 [get_ports clk_pixel]
set_property PACKAGE_PIN Y18 [get_ports clk_sys]
set_property PACKAGE_PIN AA18 [get_ports mdc]
set_property PACKAGE_PIN W17 [get_ports mdio]
set_property PACKAGE_PIN U22 [get_ports rgmii_tx_clk]
set_property PACKAGE_PIN AA19 [get_ports rgmii_tx_ctl]
set_property PACKAGE_PIN B21 [get_ports rst_n]

#! This is to fix the implementation issue: BUFG and IOB are too close
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_pixel_IBUF]

set_property PACKAGE_PIN A16 [get_ports phy_config_done]
